### ISSUE TITLE
Signing key fetch logic uses old keyservers

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/qubes-template-securedrop-workstation#13]
The SecureDrop Release Signing key is fetched from `pool.sks-keyservers.net`:

https://github.com/freedomofpress/qubes-template-securedrop-workstation/blob/d68a2d5aaa7ccf9a0da3ccaf59899d6a04524e9c/build-workstation-template#L39

We should change that to e.g. keys.openpgp.org, since that's what we recommend folks use in most contexts to fetch the key. Noticed this because the signing key expired today, and while we'd pushed a new version to keys.openpgp.org, we'd overlooked the older pools. That's now been resolved manually.

**Comment by eloquence** [comment]
This was done in #15.
