### ISSUE TITLE
Remove expired/legacy signing key

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/qubes-template-securedrop-workstation#26]
The template is still installing and importing the expired signing key. While it's theoretically harmless since it's expired, we should remove it.

**Comment by creviera** [comment]
Good call. https://github.com/freedomofpress/qubes-template-securedrop-workstation/blob/main/keys/release-key-LEGACY.asc has been expired since late June of last year I believe.

**Comment by creviera** [comment]
This has been done.
